language: cpp
env: SOURCE_JDK_TAG=jdk8u192-b12
jdk: oraclejdk8
matrix:
  include:
  - os: osx
    env: OS_BUILD=osx
    osx_image: xcode6.4
    before_install:
    - brew update
    - brew install gcc
  - os: linux
    env: OS_BUILD=linux
    dist: xenial
    sudo: required
    before_install:
    - sudo apt-get install -y libx11-dev libxext-dev libxrender-dev libxtst-dev libxt-dev
      libcups2-dev libasound2
    - sudo ln -s /usr/lib/x86_64-linux-gnu/libasound.so.2 /usr/lib/x86_64-linux-gnu/libasound.so
  - os: windows
    env: OS_BUILD=windows
    before_install:
    - choco install cygwin
    - C:\\tools\\cygwin\\cygwinsetup.exe -q -P make,unzip,automake,autoconf,zip
before_script:
  - if [[ $OS_BUILD == "windows" ]]; then
      git config --system core.longpaths true;
      git config --global core.autocrlf false;
    fi
  - unset -v _JAVA_OPTIONS;
  - git clone --depth 1 https://github.com/skybber/openjdk-build.git;
script:
  - export JDK_BOOT_DIR="$PWD/openjdk-build/jdk-8"
  - mkdir -p "$JDK_BOOT_DIR"
  - if [[ $OS_BUILD == "linux" ]]; then
      wget -q -O - "https://api.adoptopenjdk.net/v2/binary/releases/openjdk8?openjdk_impl=hotspot&os=linux&arch=x64&release=latest&type=jdk" | tar xpzf - --strip-components=2 -C ${JDK_BOOT_DIR};
      bash -c "cd openjdk-build && export LOG=info && ./makejdk-any-platform.sh --tag \"${SOURCE_JDK_TAG}\" --jdk-boot-dir ${JDK_BOOT_DIR} --target-file-name java8-openjdk-dcevm-${TRAVIS_OS_NAME}.tar.gz jdk8u";
    fi
  - if [[ $OS_BUILD == "osx" ]]; then
      wget -q -O - "https://api.adoptopenjdk.net/v2/binary/releases/openjdk8?openjdk_impl=hotspot&os=mac&arch=x64&release=latest&type=jdk" | tar xpzf - --strip-components=2 -C ${JDK_BOOT_DIR};
      JDK_BOOT_DIR="${JDK_BOOT_DIR}/Contents/Home";
      export SA_LDFLAGS=-fobjc-exceptions;
      bash -c "cd openjdk-build && export LOG=info && ./makejdk-any-platform.sh --tag \"${SOURCE_JDK_TAG}\"  --build-variant skybber  --branch master --jdk-boot-dir ${JDK_BOOT_DIR} --target-file-name java8-openjdk-dcevm-${TRAVIS_OS_NAME}.tar.gz jdk8u";
    fi
  - if [[ $OS_BUILD == "windows" ]]; then
      powershell -Command "C:\tools\cygwin\bin\bash.exe -c './build_windows.sh'";
    fi
deploy:
  provider: releases
  api_key:
  file_glob: true
  file: openjdk-build/workspace/target/*
  skip_cleanup: true
  on:
    repo: TravaOpenJDK/trava-jdk-8-dcevm
    all_branches: true
    tags: true
